export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const CHECK_SEQUENCE_SUCCESS = 'CHECK_SEQUENCE_SUCCESS';
export const LOAD_PALINDROMES_SUCCESS = 'LOAD_PALINDROMES_SUCCESS';
